# Generated by Django 5.1.4 on 2024-12-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_receipe_descrption_receipe_receipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe/'),
        ),
    ]
